### ISSUE TITLE
Tabs in flow file prevent including snow and luxe but not other libraries

### ISSUE THREAD

**Issue by hammeron-art** [underscorediscovery/flow#49]
The follow works fine:
```javascript
{
  flow : {
    build : {
      boot : 'App'
    }
  },

  project : {

    name : 'app',
    version : '0.0.1',
    author : 'hammeron-art',

    build : {
      dependencies : {
        snow : '*'
      },
      files : {
        boot : { path:'flow/boot/App.hx => haxe/App.hx', template:['project'] },
      }
    }

 },

}
```
But the same settings using tabs instead of spaces (I don't think GitHub will it with tabs here but...):
```javascrip
{
	flow : {
	 build : {
			boot: 'App'
		}
	},
	  
	project : {
		name : 'app',
		version : '0.0.1',
		author : 'hammeron-art',
		
		build : {
		    dependencies : {
				snow: '*',
		    },
		
			files : {
				boot : { path:'flow/boot/App.hx => haxe/App.hx', template: 'project' },
			}
		},
	}
}
```
Throw this error:
```
C:\HaxeToolkit\haxe\lib\flow\git\src\flow\util\util.js:48
    b.forEach(function(i) { if (r.indexOf(i) < 0) r.push(i); });
      ^
TypeError: Object project has no method 'forEach'
    at Object.exports.array_union (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\util\util.js:48:7)
    at merge_unique (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\util\util.js:165:31)
    at merge_unique (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\util\util.js:163:23)
    at merge_unique (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\util\util.js:163:23)
    at merge_unique (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\util\util.js:163:23)
    at Object.merge_unique (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\util\util.js:163:23)
    at Object.internal.cascade_project (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\project\prepare.js:219:32)
    at Object.prepare (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\project\prepare.js:58:14)
    at Object.prepare (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\project\project.js:438:21)
    at Object.run (C:\HaxeToolkit\haxe\lib\flow\git\src\flow\cmd\build\build.js:33:22)
```
Only whem snow or flow is a dependence.
Maybe its the same for other library using flow.

**Comment by underscorediscovery** [comment]
The two files you pasted are different above,
One has `template:['project']` and the other `template:'project'`.
Which doesn't make a difference in that file node specifically - but I do wonder if tabs is the only difference in your test.

Changing to tabs or spaces makes no difference for me locally,
So could you please make an isolated test case that with the two flow files so I can reproduce it?

i.e
`test/`
`   working/project.flow`
`   notworking/project.flow`

That way I can debug it.

**Comment by hammeron-art** [comment]
You are right. I tested again and the actual issue is the brackets.
https://dl.dropboxusercontent.com/u/60691076/misc/flowTest.zip
On Windows 7 Ultimate x64 I just call:
```
flow run
```
And get a error.
Replece template: 'project' to template: ['project'] in the project.flow and it works.

**Comment by underscorediscovery** [comment]
Thanks for the test :boom:
